spring.application.name=codesync-backend

server.port=8080

# ===============================
# SUPABASE POSTGRESQL
# ===============================

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.jcjxdcvngpehuwnxnkmg
spring.datasource.password=Sourabh@3235
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# JWT
# ===============================

jwt.secret=MySecretKeyForCodeSyncApplication12345678901234567890
jwt.expiration=86400000